### ISSUE TITLE
Regex not found error

### ISSUE THREAD

**Issue by Giftadene** [afizs/be-theboss-in-python#1]
I get error message after opening the chat export and it doesn't work
![e](https://user-images.githubusercontent.com/51406766/197066564-08ff7583-3ea1-4658-a4c4-adce21f8eb46.png)

also, I get the "empty data frame" message
![e1](https://user-images.githubusercontent.com/51406766/197066896-999eaa5e-5e26-4cab-87b1-40eb886b6977.png)

**Comment by muhammadalqaaf** [comment]
For the regex, it is simply just replace 'regex' with 're'. Because it was already imported in 'import re'

I also have the same issue with the empty data frame

**Comment by muhammadalqaaf** [comment]
> I get error message after opening the chat export and it doesn't work ![e](https://user-images.githubusercontent.com/51406766/197066564-08ff7583-3ea1-4658-a4c4-adce21f8eb46.png)
>
For the regex, it is simply just replace 'regex' with 're'. Because it was already imported in 'import re'

> also, I get the "empty data frame" message ![e1](https://user-images.githubusercontent.com/51406766/197066896-999eaa5e-5e26-4cab-87b1-40eb886b6977.png)

I also have the same issue with the empty data frame

**Comment by abiasykari** [comment]
I also have the same issue with empty data frame 
![image](https://user-images.githubusercontent.com/57471191/197485372-9ee733a7-390f-49b1-b1af-edb1b5a0f4da.png)

**Comment by muhammadalqaaf** [comment]
> I also have the same issue with empty data frame ![image](https://user-images.githubusercontent.com/57471191/197485372-9ee733a7-390f-49b1-b1af-edb1b5a0f4da.png)

I found the issue why you got empty data frame. It happens when the code does not match with the chat extracted data. So you need to adjust the code to match your data.

**Comment by abiasykari** [comment]
May you tell which code that not match with chat extracted data?

**Comment by afizs** [comment]
The date format must different. Please check the date format of your whatsapp chat and accordingly change the regex.

**Comment by Pascual2m** [comment]
For the regex error and the empty dataframe. I've solved this way:
![imagen](https://user-images.githubusercontent.com/120216218/206781985-b5728fc5-0ab0-4790-af68-e6895c435dce.png)

just changing the regular expression and using compile function.

**Comment by afizs** [comment]
Please use the technique provided by @Pascual2m if you face a regex issue. 

https://github.com/afizs/be-theboss-in-python/issues/1#issuecomment-1344698782
