### ISSUE TITLE
Typo in project 105

### ISSUE THREAD

**Issue by solarbroom** [afizs/be-theboss-in-python#4]
To print the value of the variable "transcript_id" with a label "transcript_id". However, the "=" sign inside the f-string is not being used correctly. To fix this issue, you can simply remove the "=" sign and the error should go away, like so:
print(f'{transcript_id}')

4th code line 18.

**Comment by afizs** [comment]
Thanks for your raising the defect. However, `{transcript_id = }` is not a typo and it will surface the output like below 👇

`transcript_id = 'remn3gxlay-66a1-450f-adca-f899954f69c0'`
